import { Inter } from "next/font/google";
import "./globals.css";
import ButtonAppBar from '../components/navbar'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <Navbar /> */}
      {/* <body className={inter.className}>{children}</body> */}
      <body className={inter.className}>
          <div className="mx-36 text-2xl">
            <ButtonAppBar />
            <div className="flex flex-col items-center text-center mt-6">
              {children} 
            </div>
          </div>
        </body>
    </html>
  );
}
